name: ext-jakartaee8-samples
on:
  workflow_dispatch:
   schedule:
     - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '15' ]
        os: [ubuntu-latest]
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup for TCK
        run: mvn clean -B -DskipTests=true install
      - name: Run TCK
        run: mvn -amd -B -P external -pl external/jakartaee-samples verify
