name: ext-tck-microprofile-jwt
on:
  workflow_dispatch:
# on:
#   schedule:
#     - cron: '0 8 * * 5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '16' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true install
    - name: Run TCK
      run: mvn -amd -B -P external -pl external/tck/microprofile/jwt verify
