name: nightly
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn --no-transfer-progress -B -DskipTests=true -DskipITs -P '!test' verify
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 Docker image
      run: |
        cd server
        docker build -f src/main/docker/Dockerfile.amd64 -t piranhacloud/server:amd64-latest .
        docker push piranhacloud/server:amd64-latest
    - name: Build arm32v7 Docker image
      run: |
        cd server
        docker build -f src/main/docker/Dockerfile.arm32v7 -t piranhacloud/server:arm32v7-latest .
        docker push piranhacloud/server:arm32v7-latest
    - name: Push multi-arch Docker manifest
      run: |
        cd server
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create piranhacloud/server:latest \
          piranhacloud/server:amd64-latest \
          piranhacloud/server:arm32v7-latest
        docker manifest annotate piranhacloud/server:latest \
          piranhacloud/server:amd64-latest --os linux --arch amd64
        docker manifest annotate piranhacloud/server:latest \
          piranhacloud/server:arm32v7-latest --os linux --arch arm --variant armv7l
        docker manifest push piranhacloud/server:latest
  maven:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn --no-transfer-progress -B -DskipTests=true -P '!test' deploy
      env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Analyze with SonarCloud
      run: |
        mvn --no-transfer-progress -B install verify site \
        sonar:sonar -Dsonar.projectKey=piranhacloud_piranha \
        -Dsonar.organization=piranhacloud -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_LOGIN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
