name: nightly
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven
      run: mvn -B -DskipTests=true -f pom.xml clean install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      run: |
        cd server
        docker build -f src/main/docker/Dockerfile.amd64 -t piranhacloud/server:amd64-snapshot .
        docker push piranhacloud/server:amd64-snapshot
    - name: Push multi-arch Docker manifest
      run: |
        cd server
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create piranhacloud/server:snapshot \
          piranhacloud/server:amd64-snapshot
        docker manifest annotate piranhacloud/server:snapshot \
          piranhacloud/server:amd64-snapshot --os linux --arch amd64
        docker manifest push piranhacloud/server:snapshot
    - name: Analyze with SonarCloud
      run: |
        mvn --no-transfer-progress -B -Ptest -Pcoverage install verify site \
        sonar:sonar -Dsonar.projectKey=piranhacloud_piranha \
        -Dsonar.organization=piranhacloud -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_LOGIN }}
